### ISSUE TITLE
Tasks overwrite erroneously when pressing Save

### ISSUE THREAD

**Issue by dotswift** [derekquinn/ios-tasks#2]
While working on the swipe to delete feature (see `feature-swipeDelete` branch) I discovered a glitch. 

Users can add tasks without problem, but once a task is deleted, subsequent added tasks may overwrite other tasks. 

There must be a problem with either `saveTask()` or the swipe to delete implementation below (found in `ViewController.swift`). I suspect somewhere I'm dealing with `index`, `count` or `newCount` incorrectly... 

```
 // swipe to delete
    func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCell.EditingStyle, forRowAt indexPath: IndexPath) {
        
        if editingStyle == .delete {
            
            let index = indexPath.row
            // remove task from array at index
            tasks.remove(at: indexPath.row)
            // remove task from tableView
            self.tableView.deleteRows(at: [indexPath], with: .fade)
            // remove object (row) from UserDefaults.standard
            UserDefaults.standard.removeObject(forKey: "task_\(index)")
            // update User Defaults count
            let newCount = tasks.count
            UserDefaults.standard.set(newCount, forKey: "count")
            // tableView reload
            self.tableView.reloadData()
        }
```
Once we get this sorted, I plan to merge this delete feature into develop for further testing.

**Comment by JorgeCurioso** [comment]
This one is tricky! My first thought was just that the index & counts are off & need to be accounted for. I think this can be managed by +1 & -1 math on the index path & task keyname you're writing to, but also gets pretty tricky to manage. To familiarize with app/view lifecycle methods a bit, and partly because UserDefaults doesn't get used much for reliable or sizable persistence. If something like this doesn't do the trick...

```swift
UserDefaults.standard.removeObject(forKey: "task_\(index + 1)")
```

...I would consider a few alternatives:
- storing to/reading from an array
- saving the persistence to any future database work you'd like to do in the future

I played around with the former & can offer a few tidbits if you're curious. Welcome to use/discard as you like!

1. I created a quick task manager class with a shared instance (singleton, not sure what this is called in other paradigms/platforms) so that we could manage 1 single set of tasks from any vantage points

```swift
struct TaskManager {
    static var current = TaskManager()

    var tasks: [String] = []

    private init() {}
}
```

(the private init is so other instances of this struct can't be created casually)

2. Added a few methods to write-to/read-from UserDefaults as before, but to an array this time (you can write objects to disk using set(Any, forKey: String), which is what. we use here for setting, and for retrieving we can call the "array" method & cast like you've done so far with String/Int values)

in: `AppDelegate`
```swift
     func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        //load the array from our user defaults
        TaskManager.current.tasks = UserDefaults.standard.array(forKey: "Tasks.current") as? [String] ?? []
         return true
     }
```

in `SceneDelegate`
```swift
     func sceneDidEnterBackground(_ scene: UIScene) {
        //Save the state when we  background/terminate the app
        UserDefaults.standard.set(TaskManager.current.tasks, forKey: "Tasks.current")
     }
```

^^ these 2 will write to & read from the `TaskManager`'s `tasks` on backgrounding & launching the app. 


3. I referenced `TaskManager.current.tasks` anywhere `tasks` is being used in your main ViewController/EntryViewController. As an example,  the ViewController's `numberOfRows` dataSource method was updated to look like this:
```swift
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return TaskManager.current.tasks.count
    }
```

and given we're just saving the whole array at once whenever we're backgrounding/quitting the app, we can just update `TaskManager.current.tasks` with creation/deletion. As an example, the EntryVC's `saveTask()` method eventually looked like this for me:
```swift
    @objc func saveTask() {
        guard let text = field.text, !text.isEmpty else { return }

        TaskManager.current.tasks.append(text)

        navigationController?.popViewController(animated: true)
    }
```

4. Instead of passing along an update block which gets executed in the EntryVC, I chose to implement `tableView.reloadData()` in the `ViewController`'s `viewWillAppear` lifecycle method. `viewDidLoad` will get called whenever any VC gets created/loaded, but won't get re-called if the VC is covered up in a navigation stack & re-shown. This is where `viewWillAppear` shines. (as you have it is totally fine as well! if loading/saving the data works as intended, reloading the data, which is based off of a shared source of truth, should update as expected)
```swift
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)

        tableView.reloadData()
    }
```

Hope there's something new or of interest in there! Cheers, and have an awesome weekend Derek!

**Comment by dotswift** [comment]
I circled back to this issue and resolved it using some of the helpful suggestions here. Many thanks @JorgeCurioso :)
